# Generated by Django 5.2.14 on 2026-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_check_in_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
