# Generated by Django 5.2.14 on 2026-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
    ]
