# Generated by Django 5.2.14 on 2026-05-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
