# Generated by Django 5.2.14 on 2026-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='allowed_radius',
            field=models.PositiveIntegerField(default=100, help_text='Allowed radius in meters'),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
